/**:
  ros__parameters:
    # I/O Topics
    input_topic: "/ouster/points"
    ground_topic: "/ground_points"
    nonground_topic: "/nonground_points"

    # --- Spatial Filter ---
    front_min_range: -30.0  # In front of lidar was - as coordinate system in our case.
    front_max_range: -1.45  
    rear_min_range: 2.0
    rear_max_range: 6.0
    crop_min_y: -7.5
    crop_max_y: 7.5
    crop_min_z: -2.0
    crop_max_z: 2.4
    leaf_size: 0.05         #For voxelgrid

    # --- Ground Segmentation Params ---
    sensor_height: 1.0
    slope_threshold_deg: 10.0
    obstacle_height_thresh: 0.20
    num_rings: 64
    horizontal_res: 512
    noise_floor: 0.10
    global_ground_tolerance: 0.20